### ISSUE TITLE
`update-ca-certificates` is missing from the dockerhub image.

### ISSUE THREAD

**Issue by sed-i** [canonical/prometheus-rock#33]
Prometheus CI now fails with `ubuntu/prometheus:2.46.0-22.04_stable` (after https://github.com/canonical/prometheus-k8s-operator/pull/535) because `update-ca-certificates` is not present in the dockerhub image.

`update-ca-certificates` is present in `ghcr.io/canonical/prometheus:dev` however.

This is likely because we added the `ca-certificates` package to the rockcraft.yaml last month, but the latest image on docker is from two months ago.
![image](https://github.com/canonical/prometheus-rock/assets/82407168/6119ecef-8278-4a5d-bcac-59a41de21dfa)

Blocked by:
- https://github.com/canonical/oci-factory/pull/58

**Comment by lucabello** [comment]
We should have the PR on oci-factory (fixed and) merged, and when we merge an update to the ROCK we should follow through all the way to that repo to make sure that PR gets merged.

**Comment by sed-i** [comment]
Confirmed with `dive` that `ubuntu/prometheus:2-22.04` has `update-ca-certificates`.
Closing.
